name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run build
        run: yarn build
      - name: Zip build files
        uses: papeloto/action-zip@v1
        with:
          files: build/
          dest: chrome-ext.zip
      - name: Upload to Google Web Store
        uses: Passiverecords/chrome-extension-upload-action@1.4.1
        with:
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          file-name: chrome-ext.zip
          app-id: ${{ secrets.APP_ID }}
          publish: true
